import { XMLParser } from "fast-xml-parser";

export type FeedItem = {
  slug: string;
  title: string;
  link: string; // source post URL
  description: string;
  contentEncoded: string;
  pubDate: string;
  guid: string;
};

const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: "@_",
});

function readText(value: unknown): string {
  if (typeof value === "string") return value.trim();
  if (typeof value === "number") return String(value);
  if (value && typeof value === "object") {
    const maybeText = (value as Record<string, unknown>)["#text"];
    if (typeof maybeText === "string") return maybeText.trim();
  }
  return "";
}

function cdataSafe(value: string): string {
  return value.replaceAll("]]>", "]]]]><![CDATA[>");
}

export function stripHtml(html: string): string {
  return html.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/<[^>]*>/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function getSlugBase(item: {
  title: string;
  link: string;
  guid: string;
}): string {
  try {
    const url = new URL(item.link || item.guid);
    const last = url.pathname.split("/").filter(Boolean).pop() ?? "";
    const byPath = slugify(last);
    if (byPath) return byPath;
  } catch {
    // noop
  }

  const byTitle = slugify(item.title);
  if (byTitle) return byTitle;

  return `post-${Date.now()}`;
}

export async function getRssItemsFromSource(limit = 50): Promise<FeedItem[]> {
  const feedUrl = process.env.RSS_FEED_URL;
  if (!feedUrl) return [];

  try {
    const res = await fetch(feedUrl, { cache: "no-store" });
    if (!res.ok) return [];

    const xml = await res.text();
    const parsed = parser.parse(xml) as {
      rss?: { channel?: { item?: Array<Record<string, unknown>> | Record<string, unknown> } };
    };
    const rawItems = parsed?.rss?.channel?.item;
    if (!rawItems) return [];

    const mapped = (Array.isArray(rawItems) ? rawItems : [rawItems])
      .map((item) => {
        const title = readText(item.title);
        const link = readText(item.link);
        const description = readText(item.description);
        const encoded = readText(item["content:encoded"]) || description;
        const pubDate = readText(item.pubDate);
        const guid = readText(item.guid) || link;

        return {
          slug: "",
          title,
          link,
          description,
          contentEncoded: encoded,
          pubDate,
          guid,
        };
      })
      .filter((item) => item.title && item.link)
      .slice(0, limit);

    const usedSlugs = new Set<string>();
    return mapped.map((item, index) => {
      const base = getSlugBase(item);
      let slug = base || `post-${index + 1}`;
      let cursor = 2;

      while (usedSlugs.has(slug)) {
        slug = `${base}-${cursor}`;
        cursor += 1;
      }
      usedSlugs.add(slug);

      return { ...item, slug };
    });
  } catch {
    return [];
  }
}

export function buildCustomRssXml(items: FeedItem[], siteUrl: string): string {
  const itemXml = items
    .map(
      (item) => `<item>
  <title><![CDATA[${cdataSafe(item.title)}]]></title>
  <link>${item.link}</link>
  <guid isPermaLink="true">${item.guid || item.link}</guid>
  ${item.pubDate ? `<pubDate>${item.pubDate}</pubDate>` : ""}
  <description><![CDATA[${cdataSafe(item.description)}]]></description>
  <content:encoded><![CDATA[${cdataSafe(item.contentEncoded)}]]></content:encoded>
</item>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
  <title><![CDATA[Custom Blog Feed]]></title>
  <link>${siteUrl}/blog</link>
  <description><![CDATA[Custom feed generated by Next.js]]></description>
  <language>ko</language>
  ${itemXml}
</channel>
</rss>`;
}
